#154 - Extend Parameter FilterOperator with value cilike (case insens…
RWS/ISHRemote pull request #156
Opened 2023-04-11 16:04 UTC by yuliamm87

2023-04-12 07:00 UTC, ddemeyer requested changes
Thanks for adding the test... These tests also need to run on 14SPx/14.0.x and will hence fail on that. In the Pester code base I've used the below if-clause within the It tests
```
if (([Version]$ishSession.ServerVersion).Major -ge 14) { # new service since 14/14.0.0
```
Can you 
1. Wrap your added test with a `-ge 15` construct
2. Add a negative test, so `-lt 15` test to see what server-side error you get on a 14SPx/14.0.x 

PS: I'll try to fix the test system used in the build... which by the way is still 14SP4/14.0.4 so will fail your test in its current state

2023-04-12 13:03 UTC, ddemeyer approved these changes

2023-04-12 16:47 UTC, yuliamm87 commented
> @yuliamm87 I would add a bit more scenarios for the CiLike:
> 
> * matching casing of the original and filter values
> * filter without %, so exact value
> * Also what happens if you pass empty value

Thank you for your comment, I will add suggested test cases, also I think we will do comprehensive tests cases on our web api story

2023-04-13 11:37 UTC, HildeVermeiren approved these changes

2023-04-13 16:28 UTC, OlegTokar approved these changes

2023-04-18 12:50 UTC, merged