#169 The pester test is aligned with the expected fields.
RWS/ISHRemote pull request #170
Opened 2023-10-04 22:29 UTC by ArianArt

2023-10-09 13:56 UTC, HildeVermeiren approved these changes

2023-10-09 14:07 UTC, OlegTokar approved these changes

2023-10-09 16:49 UTC, ddemeyer requested changes

2023-10-09 16:49 UTC, ddemeyer commented on Source/ISHRemote/Trisoft.ISHRemote/Cmdlets/Settings/CompareIshTypeFieldDefinition.Tests.ps1
> +        if(([Version]$ishSession.ServerVersion).Major -ge 15 -and ([Version]$ishSession.ServerVersion).Minor -ge 1)
What happens on version 16.0 .... 16 >= 15 AND 0 >= 1 ...

2023-10-10 10:59 UTC, HildeVermeiren approved these changes

2023-10-10 12:55 UTC, ddemeyer commented on Source/ISHRemote/Trisoft.ISHRemote/Cmdlets/Settings/CompareIshTypeFieldDefinition.Tests.ps1
> +        if((([Version]$ishSession.ServerVersion).Major -ge 15 -and ([Version]$ishSession.ServerVersion).Minor -ge 1) -or ([Version]$ishSession.ServerVersion).Major -ge 16)
Please change -ge 15 to -eq 15...

2023-10-10 14:59 UTC, HildeVermeiren approved these changes

2023-10-10 15:42 UTC, merged

2023-10-10 15:44 UTC, ddemeyer commented
Closes #169