ISHEvent and ISHBackgroundTask field information is checked to add th…
RWS/ISHRemote pull request #172
Opened 2023-10-11 11:29 UTC by ArianArt

…em to theishTypeFieldDefinitions.

2023-10-11 12:41 UTC, HildeVermeiren approved these changes

2023-10-11 13:18 UTC, OlegTokar approved these changes

2023-10-11 14:56 UTC, ddemeyer requested changes

2023-10-11 14:56 UTC, ddemeyer commented on Source/ISHRemote/Trisoft.ISHRemote/Objects/IshTypeFieldSetup.cs
> +            if (xmlDocument.SelectSingleNode("//ishtypedefinition[@name='ISHEvent']") != null)
Detecting based on the Xml means that it is API 2.5 (SOAP) API dependent... When this code is rewired to OpenAPI (JSON) then we have to adjust this code as well

2023-10-11 14:56 UTC, ddemeyer commented on Source/ISHRemote/Trisoft.ISHRemote/Objects/IshTypeFieldSetup.cs
> +            if (!hasIshBackgroundTaskFieldDefinitions)
Instead of using the earlier "detected" boolean (via de xml xpath expression) ... can you not simply check if the _ishTypeFieldDefinitions object at this point already holds ISHEvent and use that as the if-clause to decide the hardcoded piece or not...

2023-10-11 14:56 UTC, ddemeyer commented on Source/ISHRemote/Trisoft.ISHRemote/Objects/IshTypeFieldSetup.cs
> +            { AddIshEventTableFieldSetup(); }
Previous code had

1. AddIshBackgroundTaskTableFieldSetup
2. AddIshEventTableFieldSetup
3.  AddIshTranslationJobItemTableFieldSetup <-- where is this in your code?

2023-10-11 14:56 UTC, ddemeyer commented on Source/ISHRemote/Trisoft.ISHRemote/Objects/IshTypeFieldSetup.cs
> +            var ishTypeFieldDefinitions = new List<IshTypeFieldDefinition>
Can I assume that this change is just layout, and not actual changes... did not compare line-by-line?

2023-10-11 14:56 UTC, ddemeyer commented on Source/ISHRemote/Trisoft.ISHRemote/Objects/IshTypeFieldSetup.cs
> +                //internal IshTypeFieldDefinition(ILogger logger, Enumerations.ISHType ishType, Enumerations.Level level,       bool isMandatory, bool isMultiValue, bool allowOnRead, bool allowOnCrea
Same here... only layout?

2023-10-11 14:56 UTC, ddemeyer commented on Source/ISHRemote/Trisoft.ISHRemote/Objects/IshTypeFieldSetup.cs
>          private void AddIshEventTableFieldSetup()
Where is `AddIshTranslationJobItemTableFieldSetup()` function as mentioned earlier?

2023-10-11 15:43 UTC, ArianArt commented on Source/ISHRemote/Trisoft.ISHRemote/Objects/IshTypeFieldSetup.cs
> +                //internal IshTypeFieldDefinition(ILogger logger, Enumerations.ISHType ishType, Enumerations.Level level,       bool isMandatory, bool isMultiValue, bool allowOnRead, bool allowOnCrea
Yes, only layout..

2023-10-11 15:43 UTC, ArianArt commented on Source/ISHRemote/Trisoft.ISHRemote/Objects/IshTypeFieldSetup.cs
> +            var ishTypeFieldDefinitions = new List<IshTypeFieldDefinition>
The layout is changed to resolve the warning.

2023-10-12 12:38 UTC, HildeVermeiren commented on Source/ISHRemote/Trisoft.ISHRemote/Objects/IshTypeFieldSetup.cs
> +            { AddIshEventTableFieldSetup(); }
Previously we had an empty method AddIshTranslationJobItemTableFieldSetup which is not used...so do you really want to keep this empty method and put a check around it?

2023-10-12 12:56 UTC, HildeVermeiren approved these changes

2023-10-13 12:44 UTC, OlegTokar approved these changes

2023-10-16 06:54 UTC, ddemeyer commented on Source/ISHRemote/Trisoft.ISHRemote/Objects/IshTypeFieldSetup.cs
> +            { AddIshEventTableFieldSetup(); }
Although commented out, it was still a building block on route to #69 ... preferably the RetrieveTypeFieldSetup API call offers these two object types as well.

2023-10-16 06:54 UTC, ddemeyer approved these changes

2023-10-16 09:38 UTC, merged